/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Adder */

#ifndef _Included_Adder
#define _Included_Adder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Adder
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Adder_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
